server:
  shutdown: graceful
spring:
  main:
    allow-bean-definition-overriding: true
  devtools:
    restart:
      enabled: false
  data:
    mongodb:
      auto-index-creation: true
      uuid-representation: standard
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
  pid:
    file: ${instance.pid}

application:
  version: /v1
  prefix: /api
  project: /cpc
  exclude-prefix-path: springdoc
  role-type: USER
  site-id: 62a15f4ae4129b518b133128

management:
  endpoints:
    web:
      exposure:
        include: metrics, prometheus, health

logging:
  level:
    root: ${cpc.api.logging.level.root:DEBUG}
    org.springframework.data.convert.CustomConversions: ERROR
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: ${cpc.api.logging.level.mongo:DEBUG}
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
        encryptionsdk: DEBUG

    io:
      spring:
        cloud: INFO

xangle:
  host: https://pro-api.xangle.io
  disclosure-path: /xangle/v1/disclosure/list/all
  asset-list-path: /xangle/v1/asset/list
  asset-profile-path: /xangle/v1/asset/profile



---
server:
  port: 8085
spring:
  config:
    import: classpath:aws-properties.yml, classpath:springdoc.yml
    activate:
      on-profile: local
  data:
    mongodb:
      host: ${auth.mongo.host:localhost}
      port: ${auth.mongo.port:27017}
      database: ${auth.mongo.database:test}
      auto-index-creation: true
      uuid-representation: standard
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
logging:
  config: classpath:logback-spring-${spring.profiles.active}.xml
listener:
  host: http://localhost:7071


---
server:
  port: 8080
spring:
  config:
    import: classpath:aws-properties-eks-dev.yml, classpath:springdoc.yml
    activate:
      on-profile: eks-dev
logging:
  config: classpath:logback-spring-${spring.profiles.active}.xml
listener:
  host: http://k8s-systemsd-smartadm-afbac2448d-819744829f8d8a3a.elb.ap-northeast-2.amazonaws.com
---
server:
  port: 8080
spring:
  config:
    import: classpath:aws-properties-dev.yml, classpath:springdoc.yml
    activate:
      on-profile: dev
logging:
  config: classpath:logback-spring-${spring.profiles.active}.xml
listener:
  host: http://172.27.9.23
---
server:
  port: 8080
spring:
  config:
    import: classpath:aws-properties-qa.yml, classpath:springdoc.yml
    activate:
      on-profile: qa
logging:
  config: classpath:logback-spring-${spring.profiles.active}.xml
listener:
  host: http://172.27.10.20
---
server:
  port: 8080
spring:
  config:
    import: classpath:aws-properties-prod.yml
    activate:
      on-profile: prod
springdoc:
  api-docs:
    enabled: false
logging:
  config: classpath:logback-spring-${spring.profiles.active}.xml
listener:
  host: http://172.27.8.27
