server:
  shutdown: graceful
  port: 8080
spring:
  main:
    allow-bean-definition-overriding: true
  devtools:
    restart:
      enabled: false

application:
  version: /v1
  prefix: /api
  exclude-prefix-path: springdoc

management:
  endpoints:
    web:
      exposure:
        include: metrics, prometheus, health

---
spring:
  config:
    import: classpath:aws-properties.yml, classpath:springdoc.yml
    activate:
      on-profile: local
  data:
    mongodb:
      host: ${auth.mongo.host:localhost}
      port: ${auth.mongo.port:27017}
      database: ${auth.mongo.database:test}

---
spring:
  config:
    import: classpath:aws-properties.yml, classpath:springdoc.yml
    activate:
      on-profile: default
  data:
    mongodb:
      host: ${auth.mongo.host:localhost}
      port: ${auth.mongo.port:27017}
      database: ${auth.mongo.database:test}


---
spring:
  config:
    import: classpath:aws-properties-dev.yml, classpath:springdoc.yml
    activate:
      on-profile: dev

---
spring:
  config:
    import: classpath:aws-properties.yml
    activate:
      on-profile: prod
springdoc:
  api-docs:
    enabled: false
