apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpc-app-api
  namespace: NAMESPACE
  labels:
    app: cpc-app-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpc-app-api
  strategy: {}
  template:
    metadata:
      labels:
        app: cpc-app-api
    spec:
      containers:
        - name: cpc-app-api
          image: AWS_ECR_URI
          ports:
            - containerPort: 8080
          resources: {}